version: 2.1
orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@1.0
jobs:
  install-flutter:
    executor:
      name: android/android-machine
      resource-class: large
    steps:
      - checkout
      - flutter/install_android_gradle
      - flutter/install_android_gem
      - flutter/install_sdk_and_pub
      - android/create-avd:
          avd-name: myavd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: myavd
          no-window: true
          restore-gradle-cache-prefix: v1a
      - run: flutter doctor


workflows:
  flutter_workflow:
    jobs:
      - install-flutter