version: 2.1
orbs:
  flutter: circleci/flutter@1.0.0
  android: circleci/android@1.0.3
jobs:
  distribute:
    executor:
      name: android/android-machine
    steps:
      - flutter/install_sdk_and_pub
      - flutter/install_android_gradle
      - flutter/install_android_gem
workflows:
  flutter_workflow:
    jobs:
      - flutter/unit_test:
          version: 2.2.3
      - distribute