version: 2.1
orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@1.0
jobs:
  distribute:
    executor:
      name: android/android-machine
    working_directory: ~/my-flutter-project
    steps:
      - checkout:
          path: ~/my-flutter-project
      - run:
          command: |
              mkdir ~/development && cd $_
              if [ "$(uname)" == 'Darwin' ]; then
                curl -o flutter_sdk.zip https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.2.3-stable.zip
                unzip -qq flutter_sdk.zip
              elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
                curl -o flutter_sdk.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_2.2.3-stable.tar.xz
                tar xf flutter_sdk.tar.xz
              else
                echo "Your platform ($(uname -a)) is not supported."
                exit 1
              fi
              echo 'export PATH=~/development/flutter/bin:$PATH' >> $BASH_ENV
          name: Install Flutter SDK
      - run: flutter doctor
      - run: flutter pub get
      - android/create-avd:
          avd-name: myavd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: myavd
          no-window: true
          restore-gradle-cache-prefix: v1a
      - run: flutter doctor
workflows:
  distribute:
    jobs:
      - distribute