version: 2.1
orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@1.0
jobs:
  integration-test:
    executor:
      name: android/android-machine
    working_directory: ~/bicarakan-test
    steps:
      - checkout:
          path: ~/bicarakan-test
      - run: pwd
      - run:
          command: |
              mkdir ~/development && cd $_
              if [ "$(uname)" == 'Darwin' ]; then
                curl -o flutter_sdk.zip https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.2.3-stable.zip
                unzip -qq flutter_sdk.zip
              elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
                curl -o flutter_sdk.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_2.2.3-stable.tar.xz
                tar xf flutter_sdk.tar.xz
              else
                echo "Your platform ($(uname -a)) is not supported."
                exit 1
              fi
              echo 'export PATH=~/development/flutter/bin:$PATH' >> $BASH_ENV
          name: Install Flutter SDK
      - run: flutter doctor
      - run: flutter pub get
      - run: avdmanager list avd
      - run:
          name: Install emulator
          command: |
            echo "no" | avdmanager --verbose create avd --force --name "pixel_9.0" --device "pixel" --package "system-images;android-28;google_apis;x86" --tag "google_apis" --abi "x86"
      - run:
          name: Launch Emulator
          command: |
            emulator -avd myavd
          background: true
      - android/wait-for-emulator
      - run: flutter doctor
      - run:
          name: Run Flutter Integration Tests
          command: |
            flutter drive --driver=integration_test/driver.dart --target=integration_test/app_test.dart
          no_output_timeout: 20m
workflows:
  flutter_workflow:
    jobs:
      - integration-test