version: 2.1
orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@1.0
jobs:
  distribute:
    executor:
      name: android/android-machine
    steps:
      - flutter/install_sdk_and_pub
      - flutter/install_android_gradle
workflows:
  distribute:
    jobs:
      - distribute